on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akssammplereg.azurecr.io
        username: ${{ secrets.acr_akssammplereg_username }}
        password: ${{ secrets.acr_akssammplereg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/build/build-image" -f  "build/build-image/Dockerfile" -t akssammplereg.azurecr.io/akscluster:${{ github.sha }} --label dockerfile-path=build/build-image/Dockerfile
        docker push akssammplereg.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksclusterbf0e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksclusterbf0e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksclusterbf0e
        container-registry-url: akssammplereg.azurecr.io
        container-registry-username: ${{ secrets.acr_akssammplereg_username }}
        container-registry-password: ${{ secrets.acr_akssammplereg_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksclusterbf0e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akssammplereg.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth
